-- CreateEnum
CREATE TYPE "Location" AS ENUM ('CITY_OF_VANCOUVER', 'NORTH_SHORE', 'BURNABY', 'NEW_WESTMINSTER', 'DELTA_SURREY_LANGLEY', 'TRICITIES_PITT_MAPLE_RIDGE', 'RICHMOND');

-- AlterTable
ALTER TABLE "Listing" ADD COLUMN     "area" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "location" "Location" NOT NULL DEFAULT 'CITY_OF_VANCOUVER';
